name: i18n

on:
  # allow running manually
  workflow_dispatch:
  # run weekly
  schedule:
    - cron:  '30 5 * * 0'

jobs:
  i18n:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch:
          - 'master'
          - 'stable-4.4'

    steps:

    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}

    - name: "extract strings"
      run: |
        npm install
        npm run gettext:extract

    - name: "compile strings"
      run: npm run gettext:compile

    - name: "commit"
      run: |
        git config --global user.name 'GitHub Actions: i18n workflow'
        git config --global user.email 'ansible-hub-ui+i18n@example.com'

        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ansible/ansible-hub-ui.git
        git add locale/
        if git commit -m "Automated updated of i18n strings on $(date +'%Y-%m-%d')"; then
          git push --set-upstream origin
        fi
